alliance-genome/agr_literature_ui

src/actions/queryActions.js
src/components/query/BreadCrumbs.js
src/components/query/Facets.js
src/reducers/queryReducer.js

- Added two more facets to the "bibliographic data" category
- Created separate component for show more/less/all buttons
- Changed logic to manage show more/less/all buttons: hide them when no all entries already displayed
- Fixed breadcrumbs: they were displayed on separate lines for each facet, now on the same line

Scrum 1462 - Added more facets

---

src/components/search/Facets.js
src/reducers/searchReducer.js

This PR fixes the following issues:
- warning about undefined value for searchQuery text
- if you go to the search page, query for a PMID and come back, the search results load as if someone had searched for an empy string
- excluded warnings on useEffect in Facets.js

Search fixes

---

src/actions/searchActions.js
src/components/search/SearchBar.js
src/components/search/SearchOptions.js
src/reducers/searchReducer.js

Adding code to delivery pagination.  Functions are limited to First,  Last, Next, and Previous.  The first page is defined as page zero (to  make the maths easier) but displayed as page one.  Page is reset to zero  upon changing the size of pages or running another query.  Its possible that all the pagination could be moved into its own component as it get more complex... or now if we think thats necessary.
Needs the corresponding SCRUM-1356 pull from the agr_literature_service repo to function properly.

SCRUM-1356 Adding Pagination

---

src/components/search/Facets.js
src/components/search/SearchOptions.js

Fixing last page bug with perfectly divisible numbers of results, page  is reset to zero when changing facet values, added total number of pages  in pagination widget, fixed bug with empty search by disabling all  pagination on initial page load.
There is a decent amount of code in the pagination functionality that when we go to work on this again I'd probably want to move it into its own component/container.

Various Fixes

---

src/components/search/Facets.js

Selecting a facet without any text in the search bar now triggers a search

fix(search): allow search by facets only

---

src/actions/searchActions.js

It seems that this endpoint returns URL in two different fields.  The  pages field that is an array and the url field on the top level.  This  change means if the pages field exists we use the first url from that  array and if not we use the top level url.  I dont know if its possible  to have more than one entry in this array but the returns I looked at  did not seem to.  Checked the examples that Ceri provided (MGI, SGD, etc) and all appear to be going to the correct url now.

Correcting URL's

---

src/components/search/SearchResults.js

Search results throw an error if there are no xrefs.  I'm not 100% sure if this needs to be fixed here or on the API level but currently if an entry has no xrefs it will fail to load.  This seemed to happen with an entry that is fake (Testing the Test AGRKB:101000001825278) but if this is possible we need some code to make sure this wont happen to other entries.

Fixing Null Error

---

src/components/search/Facets.js
src/reducers/searchReducer.js

Removed problematic code for filter and just adding Author as another  basic facet.
Note: Show All doesn't actually show all authors... it only shows 1000.  This request seems fine and returns a lot of results but doesn't cause any errors.  We could consider adding in an overflow for these but we'd have to change the div grouping since certain labels are on the same level as the facet data.
Needs SCRUM-2148 in the agr_literature_service to work properly.

Adding in author Facet

---

package-lock.json
package.json
src/App.css
src/actions/biblioActions.js
src/components/Biblio.js
src/components/biblio/BiblioDisplay.js
src/components/biblio/BiblioFileManagement.js
src/components/biblio/NoAccessAlert.js
src/reducers/biblioReducer.js

- added new tab for file management
- two dropzone components to upload one or more files for main and supplements - drag and drop or open, multiple files and folder uploads
- table to list files associated with the reference under the dropzones, sorted by file_class and display name
- error handling with modals and an alert in case of success
- UI constraint on file names with multiple periods
- okta based extraction of MOD to associate files to
- now hiding all editors if not logged-in

Scrum 1980 - file management interface

---

src/components/search/SearchResults.js

Only split on whitespace.  Should fix html characters only getting part of their codes.

Fix abstract truncation

---

src/components/Tracker.js

Link now uses the react link and not a hardcoded localhost link.

Scrum 2427 Fixing Link

---

.env.development_devserver
src/components/Biblio.js
src/components/Tracker.js
src/components/biblio/BiblioEntity.js
src/components/biblio/BiblioFileManagement.js
src/reducers/isLoggedReducer.js

Hi @valearna and @pjhale .  This code probably works and could be merged, but making a draft PR in case either of you is really opposed to how it's changed (I left a bunch of stuff commented out instead of removing it).  Basically, when someone logs on to okta, I'm mostly using Paul's code to get the MOD, then using the old code to get whether they're a developer, and additionally now checking for Tester and POTester, and storing those as values in the store, as siblings to oktaGroups.  Then every component that would previously import getOktaModAccess and use that, can just useSelector to get it from the store, and in most cases the access is based on oktaMod + oktaDeveloper, but in the Tracker it can just use oktaMod because we explicitly don't want developer there.  I think just …

Scrum 2845

---

src/actions/searchActions.js

First does a find and replace for the OR characters... then escapes the  | character in case its in any searches.

SCRUM-2736 OR search.

---

src/actions/biblioActions.js
src/components/biblio/BiblioEntity.js

* added code to get a list of qualifiers from A-team ATP ontology
* added code to make sure some topics (GO, phenotype, headline, protein complex, other primary literature) require entity
* also make sure Omics topics (HTP Phenotype data and other HTP data) do not require entity
* for review papers, the entity is optional, but they always get 'review display' 
* for other topics like 'pathway', 'regulation', PTM, gene model etc, the entity is optional, and they will get 'additional display' only if the entity is provided.
TODO: need to fix the warning message display. Hopefully, @valearna can lead a coding session to fix this along with other warnings across UI codebase.

added code to automate qualifier addition for SGD when topics selected plus

---

src/components/ATeamAlert.js

Test won't trigger without an access Token... preventing the error if a user is either not logged in or the page hasn't gotten the token yet.

SCRUM-2492 bugfix

---

src/actions/biblioActions.js
src/components/biblio/BiblioEntity.js

- get or create "curator" source at startup
- send data according to new schema when creating new topic entity tags

Scrum 3045 - updated UI to use new topic entity tag APIs

---

src/components/biblio/topic_entity_tag/TopicEntityCreate.js

The default cache option on AsyncTypeahead component was preventing duplicate API calls, and some logic was skipped. Now setting useCache property of the AsyncTypeahead component to false.

fix(topicEntityTag): Disable caching in AsyncTypeahead component

---

src/actions/searchActions.js

Fixed the URL format used for axios POST requests by appending a slash at the end within the 'src/actions/searchActions.js' file. This modification was done to align the URL structure with our backend server's routing conventions and avoid 307 errors from nginx

Adjust axios POST request URLs in searchActions

---

src/actions/biblioActions.js
src/components/Biblio.js

Setting curie only through url parameter and not by the queryId component, which now pushes the ref curie to the history to load a new reference

Enable history navigation within biblio components

---

src/actions/searchActions.js
src/components/search/Facets.js
src/reducers/searchReducer.js

When someone is logged in the facet "in corpus or needs review" is automatically selected.  This is accomplished by another variable in the reducer that tracks is we have loaded these yet.  Users can deselect the preloaded facet and it will only return on a page refresh.
Keeping as draft until Kimberly can look at it.

Adding Mod Preferences

---

src/components/search/SearchLayout.js

Fixed the search UI to make the facets section always visible on the left side of the screen as users scroll down the search results page. Also added code to make facets section scrollable.
Should we put the css code for this in App.css?

Fixed the search UI to make the facets section always visible 

---

src/actions/searchActions.js
src/components/biblio/topic_entity_tag/TopicEntityTable.js
src/components/search/Facets.js

Author filter was broken because the function did not have the exclude facet value.  This is because we pass in a huge list of variables for every ES call... but now we grab all those from state instead.  Also created a function to build search params values so that this code is not duplicated.
This also fixes display tag name since we did that in the AG Grid demo.

Fixing Author Filter and Code Cleanup

---

src/components/AgGrid/ValidationByCurator.jsx

Confidence level should always be null.

Bugfix for SCRUM-3603 - confidence level

---

src/actions/searchActions.js
src/components/search/Facets.js
src/reducers/searchReducer.js

* adding "apply selections to single tag" checkbox
* adding a warning message when multiple topics or multiple confidence levels are selected and the "apply selections to single tag" checkbox is checked
* adding code in searchActions.js to preprocess facets selection data to construct nested search data structure

update code to work with nested object type for topic_entity_tags and tet single tag search option

---

src/components/search/Facets.js

Making sure the buttons always render on their own line.  Also adding padding to the bottom of the facet to give a bit more room between date elements.

Style fixes for SCRUM-3299

---

src/App.css
src/App.js
src/actions/biblioActions.js
src/components/AgGrid/EntityFilter.jsx
src/components/biblio/topic_entity_tag/TopicEntityTable.js
src/index.js
src/reducers/biblioReducer.js

Adds the entity filter.  Functions almost exactly the same as the species filter but we dont need to use any mappings for the ID.  This filter also has the option for "None" to show entries that have no entity type.  Adds css that applies to the other filter to make it look nice.  Changes the location of the app.css import so that bootstrap styling does not override our local style.

Adding Entity Filter

---

src/actions/searchActions.js
src/components/search/Facets.js
src/reducers/searchReducer.js

- Added the new facets
- Added the ability to "show more" to all TET facets
- Removed extra calls to API to get initial facets
- Added a new redux state variable to avoid sending search requests until all default facet values are set (only mod_in_corpus_or_needs_review per logged in user for now)

Scrum 3678 Added facets for TET source fields

---

package.json
src/actions/biblioActions.js
src/components/AgGrid/EntityFilter.jsx
src/components/AgGrid/EntityTypeFilter.jsx
src/components/AgGrid/MultiFilter.jsx
src/components/AgGrid/TopicFilter.jsx
src/components/biblio/topic_entity_tag/TopicEntityCreateSGD.js
src/components/biblio/topic_entity_tag/TopicEntityTable.js
src/reducers/biblioReducer.js

1. adding a generic multi filter that will shows up as a typeahead if there are more than 10 options; otherwise shows up as a list of checkboxes for the options.
2. creating TopicFilter and EntityFilter by calling the generic MultiFilter
3. applying the TopicFilter and EntityFilter  to the Topic and Entity Columns in the Topic Entity Table
4. Renaming original EntityFilter to EntityTypeFilter (it is for entity types, not for entities)

adding multi filter to Topic and Entity columns

---

src/components/biblio/topic_entity_tag/TopicEntityTable.js

@sweng66 @pjhale There's some warnings, and I fixed a few that seemed obvious.  There's still a few more though
Line 51:6:    React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array        react-hooks/exhaustive-deps
Line 79:6:    React Hook useEffect has a missing dependency: 'fetchTableData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
Line 348:9:   'nameFormatter' is assigned a value but never used                                                                 no-unused-vars
Line 425:19:  'setColDefs' is assigned a value but never used   
348 ->  can we just get rid of that ?  It doesn't seem to be used anywhere
425 ->   const [colDefs, setColDefs] = useState(cols);
colDefs is only used in one place …

add more fields to TET table column options.  clean up some warnings.

---

src/actions/searchActions.js
src/actions/sortActions.js
src/components/Sort.js
src/components/search/Facets.js
src/reducers/sortReducer.js

* adding paper into log-in user's mod corpus
* adding paper into log-in user's mod corpus plus directing curators to TET page
* discarding paper from log-in user's mod
* adding "Update Sorting" button on the top (along with the one at the bottom) to discard/add multiple papers at the same time
* also fixed the search code to handle tester properly (for missing PDF icon issue in search result page)

updating sort page to work for single reference

---

src/components/Reports.js
src/components/biblio/topic_entity_tag/TopicEntityTable.js

This looks bad, but has the functionality as described in the ticket.

Scrum 4796

---

.github/workflows/claude-code-review.yml

- Remove hardcoded pr_size_threshold and skip_threshold
- Let workflow inherit defaults from alliance-genome/.github
- Centralized thresholds: skip ≤3 lines, zen >40 lines
- Supports Skip 10%, Zen 50% strategy across all repos

Use centralized Claude review thresholds from .github repo
