alliance-genome/agr_literature_ui

.env, src/config.js
=> Login with microsoft

.env, Dockerfile, docker-compose.yml, nginx.conf
- created dockerfile with separate stages for build and deployment
- deployment based on nginx
- added docker-compose configuration for easy deployment (docker-compose up)
- added PORT variable to .env to set deployment port
=> feat(docker): dockerized ui

src/components/query/Facets.js, src/components/query/SearchLayout.js
Fixed layout on large displays
=> Scrum 1489 - faceted search

src/components/query/Facets.js, src/components/query/SearchLayout.js
Added container with three columns to align checkboxes, facets values and counts
=> Scrum 1489 - faceted search counts on the right

src/actions/sortActions.js, src/components/Sort.js, src/components/query/SearchBar.js, src/components/query/SearchLayout.js, src/components/query/SearchOptions.js, src/components/query/SearchResults.js, src/reducers/sortReducer.js
- Added spinners inside search buttons for Query and Sort pages
- Removed white div under search box in Query page
- Added 'no results found' for both pages
=> Scrum 1502 spinners + improved layout

src/actions/queryActions.js, src/components/query/BreadCrumbs.js, src/components/query/Facets.js, src/components/query/SearchLayout.js, src/components/query/SearchOptions.js, src/reducers/queryReducer.js
- Added bread crumbs for facets
- changed logic for adding/removing facets values
=> Scrum 1461 bread crumbs

Dockerfile, docker-compose.yml
Removed nginx config file from docker-compose volumes as it was causing issues with jenkins. I had to set up jenkins by using docker commands directly and not docker-compose, at least for now. Merging this PR into main should also trigger a new build
=> Jenkins test

src/App.css, src/components/search/SearchResults.js
Added xRefs, Authors, pub date, and abstract.  Needs the corresponding 
pr in the API to have access to this data.  Adds red obsolete to 
obsolete xrefs and cuts abstracts down to 500 chars.
=> SCRUM-1770 Adding Extra Fields to search results

src/actions/searchActions.js, src/components/search/Facets.js, src/components/search/SearchBar.js, src/reducers/searchReducer.js
UI component for author filtering
=> SCRUM-2148 UI Changes for author filtering

package.json, src/actions/searchActions.js, src/components/search/Facets.js, src/reducers/searchReducer.js
Moving author filter to its own component, moving that component to the  top of the author box, adding a clear author filter button, removing  authorFilter from text box after selecting author.
=> Author Filter Tweaks

src/actions/searchActions.js, src/components/search/Facets.js, src/reducers/searchReducer.js
Adding the date filtering for both date added to pubmed and date modified in pubmed.  As per the usual there is another PR in the API repo that will need to be run in tandem with this.
=> Adding Date Filtering to Facets

src/App.css, src/components/search/SearchResults.js
Adds UI code for highlighting.  Needs the API PR to work correctly.
=> Scrum-1355 Highlighting

src/components/search/Facets.js
Small PR to fix a bug with the date facet and respond to some feedback from the search group.  The date facet now stays open when a date is selected on the page.  In addition this is moved to the top since it doesn't work with breadcrumbs yet.
=> Scrum 2117 fix

src/actions/searchActions.js, src/components/search/Facets.js, src/components/search/SearchBar.js, src/components/search/SearchOptions.js, src/reducers/searchReducer.js
Added the ability to search via different fields.  Will need the API pull to function correctly.  Also did a clean up of the search references function.  This function does not require any arguments anymore but draws directly from the redux store.  Leaving this as draft until we can test with the new analyzer/fields in ES.
=> Scrum-1464 Adding Search Types

src/actions/biblioActions.js, src/components/Biblio.js, src/components/biblio/BiblioEntity.js, src/reducers/biblioReducer.js
- using new api endpoints to get the list of tags and the curie->name mappings
- removed data and fetch functions from the redux actions/reducers - now managed in the component
- copied pagination component from search
- set default page size to 10
=> Scrum 2474 - added pagination to topic and entity tags page

src/components/search/SearchBar.js
Adding UI elements for curie and Xref search to use ES.
=> SCRUM-2082 Adding Curie and Xref Search

src/components/biblio/BiblioEntity.js
- added icon to sort by entity type
- icon changes color when clicked to indicate that the table is being sorted by entity type
- multiple clicks alternate between asc and desc sorting
- modified api call to include new sort by parameters
=> Scrum 2473 sort by entity type

src/components/biblio/BiblioEntity.js
Clicking three times goes back to non-sorted results
=> feat(topic_entity_tag): new icons for sorting

src/App.css, src/actions/searchActions.js, src/components/search/SearchBar.js, src/reducers/searchReducer.js
UI component to the partial match ticket.  This adds the UI elements and an additional field passed to the API for this in addition to some tweaks to the css to make the inputGroup look a bit better. 
Needs the SCRUM-2489 API ticket to work correctly.
=> Scrum-2489 Parital Matches

src/components/search/SearchResults.js
Added back in the dangerousHTML display so italics etc show up  correctly.
=> Fix clobbered some previous changes

src/components/search/Facets.js, src/components/search/SearchBar.js, src/components/search/SearchOptions.js, src/reducers/searchReducer.js
Changed references to the 0'th page into the 1st page in the various  components.
=> SCRUM-2576 Changing page indexing from 0 to 1

src/components/search/Facets.js
Formats the date to YYYY-MM-DD for passing to ES
Prevents a different date from being passed to the API via timestamp issues.
=> Adding format date range function

src/components/Biblio.js, src/components/biblio/BiblioFileManagement.js
Added check for open_access in biblio component for referencefiles and in file management tab
=> Scrum 2701 - grant access to all files if reference is open_access

src/components/biblio/BiblioFileManagement.js
Using API delete function as it was already written so no API changes.
https://agr-jira.atlassian.net/browse/SCRUM-2227
=> SCRUM-2227 Adding in delete functionality

src/components/biblio/BiblioFileManagement.js
* display a pulldown menu for available copyright licenses
* add the newly selected license into copyright_license_id column in reference table through api
=> adding a row (open access) into file management page 

src/App.css, src/components/AppWithRouterAccess.js, src/components/NavigationBar.js, src/components/Tracker.js, src/reducers/index.js, src/reducers/trackerReducer.js
Will need merge to main since the db has changed and api calls are  failing.
=> File management page

src/components/Sort.js
I am not sure if I got the access control here. please update whatever you think it is needed.
=> scrum-1386 link main PDF to sort

src/components/Sort.js
=> scrum-1386 fix spinner

src/components/search/SearchBar.js
=> scrum-2673 add citation to search

src/actions/trackerActions.js, src/components/Tracker.js, src/reducers/trackerReducer.js
Moved actions to new file, added loading overlay, added to reducer.
Needs SCRUM-2640 PR in the API to work correctly.
=> Order by Date SCRUM-2640

src/actions/trackerActions.js, src/components/Tracker.js, src/reducers/trackerReducer.js
Also moves the date sort from the top bar into the column.
=> Adding Pagination

src/actions/trackerActions.js, src/components/Tracker.js, src/reducers/trackerReducer.js
Default returns the normal data set... the other two return only  references that have a specific workflow tag.
=> Adding Filter

src/components/Sort.js, src/reducers/sortReducer.js
UI can display multiple main file for sort, see  https://dev3005.alliancegenome.org/sort, try "FB" with referencefile records.
=> Scrum 2912 sort retrieve referencefile

src/components/biblio/BiblioEntity.js
…ther additional literature', 'other primary information'
=> adding ATP ID for 'other HTP data' and place holders for other topics that are not in ATP yet

src/actions/searchActions.js
Changes the keyword AND to + and adds a backslash to any plus inputted.
=> SCRUM-2672 AND Search

src/App.css, src/actions/biblioActions.js, src/components/ATeamAlert.js, src/components/Sort.js, src/components/biblio/BiblioEntity.js, src/reducers/biblioReducer.js
Warning for ateam api being down
=> SCRUM-2492 A Team Warning

src/components/search/Facets.js, src/reducers/searchReducer.js
Adding the Mod reference type to the faceted search.  Needs API changes to work in another PR.
=> SCRUM-2144 Adding Mod Reference Type

src/components/biblio/BiblioEntity.js
I realize this is an ugly html table (not responsive) and it's repeating some code, it's just a placeholder for Ceri to see what this kind of view would look like.
=> ugly table to display API data in html table

src/components/biblio/BiblioEntity.js
I think that this is now ready to be merged into main @azurebrd
=> Scrum 3241 - new topic entity tag table (functional mockup)

src/components/AppWithRouterAccess.js, src/components/biblio/BiblioRawTetData.js, src/components/biblio/topic_entity_tag/TopicEntityTable.js
Need SCRUM-3314-api to be committed first.
=> remove authorisation for restapi as ateam access now generated in api

src/components/biblio/FetchTypeahead.js, src/components/biblio/topic_entity_tag/TopicEntityCreate.js
1. set the entity_type to "species" if selected tpoic is "species".
2. set the entity_list as autocomplete field when selected tpoic is "species"
3.  set the entity_list as textarea when selected tpoic is not "species"
=> Adding a toggle for entity_list to toggle between autocomplete and textarea 

src/components/ATeamAlert.js, src/components/biblio/topic_entity_tag/TopicEntityCreate.js
use new url and look for specific data to pass. tick boxes aligned left on tet editor.
=> new url for apteam check and align left on tick boxes

src/components/ATeamAlert.js, src/components/Create.js, src/components/biblio/topic_entity_tag/TopicEntityCreate.js, src/components/biblio/topic_entity_tag/TopicEntityCreateSGD.js, src/components/biblio/topic_entity_tag/TopicEntityTable.js
Fixes to remove warnings on compilation. Should be straight forward. 'warningMessage' is never set so no point having that code that checks for this and gives error message is the only thing that is not straight forward.
=> fixes to remove warning on compilation

src/components/biblio/topic_entity_tag/TopicEntityCreate.js
so only shows autocomplete option when 'species' is selected for topic
=> fixed to reset the autocomplete/list switch option for entity_list

src/components/biblio/topic_entity_tag/TopicEntityTable.js
for the tags that created through UI - abc_literature_system
=> fixed to display ECO name instead of the evidence code from the database 

src/actions/biblioActions.js
for tags added by curators through UI
=> fixed to replace the placeholders to real values for tet source

src/actions/biblioActions.js, src/components/biblio/topic_entity_tag/TopicEntityTable.js, src/reducers/biblioReducer.js
reset the pagesize to default value when switching to a different paper.
=> fixed to preserve pagesize when navigating between tabs for the same paper and 

src/components/biblio/topic_entity_tag/TopicEntityTable.js
The display names in the following columns are clickable:
* topic
* entity_type
* entity
* species
* source evidence
=> Creating a modal popup to show curie for the given ontology display name when clicking on the display names in the tet table 

src/components/biblio/topic_entity_tag/TopicEntityCreate.js, src/components/biblio/topic_entity_tag/TopicEntityTable.js
I want to show this to Kimberly at standup before merging
=> Added 'null' value to 'negated' field and changed checkbox into select

src/actions/searchActions.js, src/components/search/BreadCrumbs.js, src/components/search/Facets.js
Added mod ref type, alliance type, and pubmed type to the negated facets.  The facets that get this treatment are stored in an array.  Also modified the show more/less/all function.
=> Adding More Exclude Facets

src/components/biblio/topic_entity_tag/TopicEntityTable.js
… tag count will be refreshed automatically
=> fixed the total tag count bug when deleting a tag

src/components/biblio/topic_entity_tag/TopicEntityCreate.js, src/components/biblio/topic_entity_tag/TopicEntityCreateSGD.js
and remain visible until the user clicks on this button
=> modified code so that the tag duplicate alert messages display a "close' button

package-lock.json, package.json, src/components/biblio/topic_entity_tag/TopicEntityTable.js
Also added missing dependency on fontawesome icons
=> Do not load mappings on page changes

src/actions/biblioActions.js, src/components/biblio/topic_entity_tag/TopicEntityCreate.js
=> Scrum 3453 2

src/actions/biblioActions.js
Blooming slow due to API call being super slow!! But it works. Needs agr_literature_service updated first to see transform.
=> store modEntityId for constructs and not name

package.json, src/App.css, src/actions/biblioActions.js, src/components/AgGrid/SpeciesFilter.jsx, src/components/AgGrid/TopicEntityTagActions.jsx, src/components/biblio/topic_entity_tag/TopicEntityTable.js, src/reducers/biblioReducer.js
=> Integrating AG Grid into the table

src/actions/biblioActions.js
small fix to allow multiple values.
=> allow multiple constructs

src/components/AgGrid/TopicEntityTagActions.jsx, src/components/biblio/topic_entity_tag/TopicEntityTable.js
Removes more code and uses names from the API return and not direct from A team.  Also fixes some bugs from adding and removing code.
=> Scrum 3402 fixes

.env.dev_3001, .env.development
=> Added SGD API URL

src/actions/biblioActions.js, src/actions/searchActions.js, src/components/biblio/topic_entity_tag/TopicEntityCreateSGD.js
Added fixes to send data for all TET facets
=> Scrum 3678

src/actions/biblioActions.js, src/components/biblio/topic_entity_tag/TopicEntityCreateSGD.js
also updated SGD version of TET creator to set the entity type based on the topic selected.
=> adding code to validate systematic names for genes

src/actions/searchActions.js, src/components/search/BreadCrumbItem.js, src/components/search/BreadCrumbs.js, src/components/search/Facets.js, src/reducers/searchReducer.js
Add various dates to the breadcrumb display on ABC search page
=> Scrum 4030

src/components/biblio/topic_entity_tag/TopicEntityCreate.js
Only a couple of changes here, more changes on the WB API side.
=> Scrum 4106

src/components/biblio/topic_entity_tag/TopicEntityCreate.js
this fixes the entity type select being set to null in edit mode
=> Automatically set entity type according to topic only if not in edit mode

src/components/AgGrid/TopicEntityTagActions.jsx
Deleting now only requires one click after bringing up the conformation box.  Also added some formatting here and fixed the X button in the modal not working.  Removed unused code.
=> Fixing Excess Clicks

src/components/search/Facets.js
Language is its own facet now.  Also adds lang = English when mod prefs are loaded.
=> Adding Language

src/components/biblio/topic_entity_tag/TopicEntityTable.js
The props are now updated on rowUpdate so a further update has the correct data.
=> Fixing Bug

src/components/Sort.js, src/components/biblio/BiblioWorkflow.js
and disabled the Workflow create section in workflow Editor page
=> updated Sort page to store the new referencetype (Experimental/Not_experimental/Meeting_abstract) in MRT table

src/App.css, src/components/search/SearchResults.js
Adds a file download component.  Should select the proper pdf based on mod.  Will not work if not logged in.
=> Adding File Download Button

src/components/biblio/topic_entity_tag/TopicEntityTable.js
Also, avoid calling the API twice when loading the data for the first time
=> Scrum 4390 - call TET API only once (and not an infinite number of times)

src/components/biblio/BiblioFileManagement.js
and hide the file upload section if the paper is outside logged-mod.
=> adding code to show 'Add this paper to corpus' if the paper is not in logged-in user's mod

src/actions/biblioActions.js, src/components/AgGrid/TopicEntityTagActions.jsx, src/components/biblio/topic_entity_tag/TopicEntityTable.js, src/reducers/biblioReducer.js
Adds new button for validated tags.  Only Shows when there is a validating tag.
Needs API PR to function
=> Adding Filter for Validated Tags.

src/components/biblio/BiblioFileManagement.js
and to give curators the options to choose to keep OR delete manual tet tags after deleting a main PDF. Also refactored the FileEditor
=> adding code to catch / display the response.data.detail from 'delete' PDF API

src/components/biblio/BiblioFileManagement.js, src/components/biblio/topic_entity_tag/TopicEntityCreateSGD.js
* made the 'Submit' button smaller
* made the 'Submit All' button to have blue background
* added margin space between two buttons
* passing ATP ID for manual indexing in progress when 'Submit' button is pressed
* passing ATP ID for manual indexing complete when 'Submit All' button is pressed
* also fix the file management tab to display pdf_type not just special pdf type
=> fixed SGD TET UI to pass a new parameter index_wft to TET create endpoint to add manual indexing workflow tags

src/components/Sort.js, src/components/biblio/BiblioFileManagement.js
Also adding back WB prepublication pipeline papers to the Sort page
=> updated code to refresh the workflow section when anything is changed in FileEdit section

src/actions/biblioActions.js, src/components/biblio/FetchTypeahead.js, src/components/biblio/topic_entity_tag/TaxonUtils.js, src/components/biblio/topic_entity_tag/TopicEntityCreate.js, src/components/biblio/topic_entity_tag/TopicEntityCreateSGD.js, src/components/biblio/topic_entity_tag/TopicEntityTable.js, src/reducers/biblioReducer.js
Also asked ChatGPT to clean up TopicEntityCreateSGD.js...
=> updated to replace A-team API calls with newly set up ABC API calls

src/components/search/Facets.js
and by default, they are closed
=> adding code to make sub-categories expandable / closable  

src/components/Sort.js, src/components/biblio/BiblioEditor.js, src/components/search/BreadCrumbs.js
when the paper has manually added topic/entity tags
=> Update BiblioEdit and Sort UI to catch api error and display a warning when removing a paper out of corpus 

src/components/biblio/topic_entity_tag/TopicEntityCreate.js
Needs to be merge AFTER api PR.
=> Add mod to search topic call

package-lock.json, package.json
caused by the old versions of some packages
=> fixed package.json & package-lock.json to solve the github reported security issues

src/components/search/SearchLayout.js
so the resize handle will still work when facet panel scroll bar appears (when expanding categories/subcategories)
=> fixed to move resize handle out of facet panel scroll bar

package.json, src/components/Reports.js
=> Scrum 4282 backup

package.json, src/App.js
=> Adding Cache-Buster

src/components/Reports.js
Reopening this branch... added a date converter and the papers here are now clickable with a link that goes to the biblio page.  Also added padding between the two tables.
=> Scrum 5074

src/actions/biblioActions.js, src/components/biblio/BiblioEditor.js, src/reducers/biblioReducer.js
A large chunk of the changes is moving a block of code into an else section
=> Scrum 5230

.github/workflows/claude-code-review.yml
- Uses centralized workflow from alliance-genome/.github
- Focuses on React/Redux patterns, XSS prevention, and UX issues
- No database focus as this is a pure frontend application
- Configured for 60 max turns to handle complex PRs with zen tools
- Enables multi-model analysis for PRs >300 lines
=> Add Claude Code centralized workflow for React frontend

src/components/biblio/BiblioWorkflow.js
- getting and updating the data in the new table 'indexing_priority'. Also fixed to display the confidence score if it is available
=> fixed code to get / patch indexing priority data with two new endpoints

src/actions/biblioActions.js, src/components/AgGrid/TopicEntityTagActions.jsx, src/components/AgGrid/ValidationByCurator.jsx, src/reducers/biblioReducer.js
- fixed validation icons with data novelty column
- added spinners after clicking validation icons + new "deleting..." spinner
- reload tet table after deletion to update all validation values
=> feat: enhance biblio actions with loading state and update handling for validation and tag deletion
